name: Awesome Research Group
url: http://flaglab.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: labhead
    name: Principal Investigators
  - key: postdoc
    name: Post-docs
  - key: predoc
    name: Doctoral Candidates
  - key: ugrad
    name: Students
  - key: alumni
    name: Alumni
  - key: collab
    name: Collaborators
  
# Number of news stories on the front page.
front_page_news: 0

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: Members
    link: /members.html
  - title: Research Areas
    link: /research-areas.html
  - title: Publications
    link: /publications.html
  - title: Collaborators
    link: /collaborators.html
  - title: Artifacts
    link: /artifacts.html
